export const amenities_list = ['Breakfast',
    'Locker',
    'Kitchen',
    '24/7 Online Support',
    'High Speed Wifi',
    'Air Conditioner',
    'Shop Near',
    'Single Bed',
    'Terrace',
    'Double Bed',
    'Room Service',
    'Parking',
    'Mini Bar',
    'Towels',
    'Cleaning',
    'Shower',
    'Smart Security',
    'Expert Team'];